### PR TITLE
add new PSBreakEvent

### PR DESCRIPTION
**Pull request by rinpr**
this event will called if the player has broken the protection stone. this might be useful for other plugin's addon or skript developer.

### CODE REVIEW

**Comment by espidev** [comment]
Note that this event would fire even if the player doesn't have permission to break the block (is that intended?), because it's early in the event chain.

I recommend naming it `PSBreakProtectBlockEvent`

**Comment by espidev** [comment]
Perhaps you want to add the event trigger here: https://github.com/espidev/ProtectionStones/blob/master/src/main/java/dev/espi/protectionstones/ListenerClass.java#L174

This is after the player's permission is checked.

**Comment by rinpr** [comment]
fixed

**Comment by espidev** [comment]
Would you be open to renaming the event to `PSBreakProtectBlockEvent`? I think it's a bit more clear and differentiates from PSRemoveEvent.

**Comment by rinpr** [comment]
sure Ill change it immediately

**Comment by espidev** [comment]
Thank you!

**Pull request merged**
