### PR TITLE
breaking protection stones now trigger PSRemoveEvent

### PR DESCRIPTION
**Pull request by rinpr**
might be useful for plugin developers

### CODE REVIEW

**Comment by espidev** [comment]
PSRemoveEvent is only supposed to be triggered when a region is removed (ex. https://github.com/espidev/ProtectionStones/blob/master/src/main/java/dev/espi/protectionstones/PSStandardRegion.java#L498), this will cause issues with existing event handlers since it will trigger even if the region isn't removed...

Perhaps you want to introduce a new sort of event? What is the usecase here?

**Comment by rinpr** [comment]
> PSRemoveEvent is only supposed to be triggered when a region is removed (ex. https://github.com/espidev/ProtectionStones/blob/master/src/main/java/dev/espi/protectionstones/PSStandardRegion.java#L498), this will cause issues with existing event handlers since it will trigger even if the region isn't removed...
> 
> Perhaps you want to introduce a new sort of event? What is the usecase here?

I tried to add a protection stone breaking fee with my other plugins, and I noticed that the PSRemoveEvent is not triggered when breaking a ProtectionStone. So, I attempted to patch that up. If I don’t want to create a new event for this, should I add a new RemoveCause to the existing PSRemoveEvent?

**Comment by espidev** [comment]
>  I noticed that the PSRemoveEvent is not triggered when breaking a ProtectionStone.

It doesn't trigger at all? That would be a bug... If the region is successfully removed it should trigger

**Comment by rinpr** [comment]
Oh sorry what I meant is it triggered twice

**Comment by rinpr** [comment]
> It doesn't trigger at all? That would be a bug... If the region is successfully removed it should trigger

Oh sorry what I meant is it triggered twice

**Pull request closed without merging**
